# Generated by Django 4.1.5 on 2023-01-26 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("added", models.DateTimeField(auto_now_add=True)),
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Joke",
            fields=[
                ("setup", models.CharField(max_length=500)),
                ("punchline", models.CharField(blank=True, max_length=500, null=True)),
                ("author", models.CharField(blank=True, max_length=200, null=True)),
                ("added", models.DateTimeField(auto_now_add=True)),
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "joke_anime",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.anime",
                    ),
                ),
            ],
        ),
    ]
